version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Dependabot doesn't currently support wildcard or multiple directory declarations within
  # a dependabot configuration, so we need to add all directories individually
  # See: github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "terraform"
    directory: "/terraform/environments"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/analytical-platform-management"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/bichard7"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/bootstrap/delegate-access"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/bootstrap/secure-baselines"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-logging"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-network-services"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-sandbox"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-security"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-shared-services"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/core-vpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/justice-on-the-web"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/remote-supervision"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/github"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/github/modules/repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/github/modules/team"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modernisation-platform-account"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/bastion_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/core-vpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/core-vpc-tgw-routes"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ec2-tgw-attachment"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/member-vpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ram-ec2-retagging"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ram-principal-association"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ram-resource-share"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/vpc-nacls"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/vpc-tgw-routing"
    schedule:
      interval: "daily"
