name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    paths: 'source/**'

jobs:
  check-links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.2
    steps:
    - uses: actions/checkout@v2
    - name: htmlproofer
      run: /publishing-scripts/publish.sh no-repository-changes
