---
name: core-vpc-production-deployment

on: 
  push:
    branches:
      - main
    paths:
        - 'environments-networks/*-production.json'
  pull_request:
    branches:
      - main
    paths:
        - 'environments-networks/*-production.json'
    workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
  TF_ENV: "production"

defaults:
  run:
    shell: bash

jobs:
  core-vpc-production-deployment-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.4
          terraform_wrapper: false
 
      - name: Run core-vpc terraform plan
        run: |
          # Test if this is a PR or PULL event

          #USE IF RUNNING IN GITHUB ACTIONS
          if [ ! -z ${{ github.event.pull_request.number }} ]
          then

          #USE IF USING ACT
          # if [ ! -z ${PULL_REQUEST_NUMBER} ]
          # then

          #CONFIGURE TERRAFORM AND WORKSPACE
          bash scripts/terraform-init.sh terraform/environments/core-vpc
          terraform -chdir="terraform/environments/core-vpc" workspace select "core-vpc-${TF_ENV}"

          #RUN TERRAFORM PLAN
          PLAN=`bash scripts/terraform-plan.sh terraform/environments/core-vpc | tee /dev/stderr | grep '^Plan: \|^No changes.'`
          PLAN="> TERRAFORM PLAN RESULT - core-vpc - ${TF_ENV}
          ${PLAN}"
          bash scripts/update-pr-comments.sh "${PLAN}"
          fi
        env:
          SECRET: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

  core-vpc-production-deployment-apply:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    needs: [core-vpc-production-deployment-plan]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.4
          terraform_wrapper: false

      - name: Run Terraform apply in terraform/environments/core-vpc
        run: |
          bash scripts/terraform-init.sh terraform/environments/core-vpc
          terraform -chdir="terraform/environments/core-vpc" workspace select "core-vpc-${TF_ENV}"
          bash scripts/terraform-apply.sh terraform/environments/core-vpc
          echo "Terraform apply finished"
    
  member-account-ram-associaton:
    runs-on: [ubuntu-latest]
    if: github.event.ref == 'refs/heads/main'
    needs: [core-vpc-development-deployment-apply]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed files
        id: new_account
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r HEAD^..HEAD | awk '{print $1}' | grep "terraform/environments/*" |  cut -d/ -f3 | uniq | xargs)"
      - name: Set RAM assocation for member account
        run: |
          if [ ! -n ${{ steps.new_account.outputs.files }} ]
          then
          for i in ${{ steps.new_account.outputs.files }}
          do
          echo "[+] Setting up RAM asocation for ${i}"
          bash scripts/member-account-ram-association.sh ${i} ${TF_ENV}
          done
          else
          echo "[+] There were no new AWS member accounts to process"
          fi