name: "Terraform: modernisation-platform-account"

on:
  push:
    paths:
      - 'terraform/modernisation-platform-account/**'
      - '!**.md'
      - '.github/workflows/modernisation-platform-account.yml'
      - 'collaborators.json'
      - '.github/workflows/reusable_terraform_plan_apply.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/modernisation-platform-account/**'
      - '!**.md'
      - '.github/workflows/modernisation-platform-account.yml'
      - 'collaborators.json'
      - '.github/workflows/reusable_terraform_plan_apply.yml'
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  modernisation-platform-account-plan-and-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      working-directory: "terraform/modernisation-platform-account"
    secrets:
      modernisation_platform_environments: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
