name: "Terraform: single-sign-on"

on:
  push:
    paths:
      - 'terraform/single-sign-on/**'
      - '.github/workflows/terraform-single-sign-on.yml'
      - '.github/workflows/reusable_terraform_plan_apply.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/single-sign-on/**'
      - '.github/workflows/terraform-single-sign-on.yml'
      - '.github/workflows/reusable_terraform_plan_apply.yml'
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  single-sign-on-plan-and-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      working-directory: "terraform/single-sign-on"
    secrets:
      modernisation_platform_environments: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
      gh_workflow_token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}